### ISSUE TITLE
Log event emulator

### ISSUE THREAD

**Issue by hhcalder92** [christopher-henderson/Asynchronous#1]
I am trying to create an log event emulator that will take some number n and create n events per second.  The events don't have to be evenly space spaced out, as long as they happen in the same second. I was able to achieve this with python. Once i get past 15k events per second, the event generator cannot produce keep up. 
Thus, i turned to multithreading since each event is not depended on one another. 

JK suggested this module, do you suggest it? 

Requirements:
All events go to same place 
either to stdout or socket

I am currently using sched and thread libraries.

**Comment by christopher-henderson** [comment]
You definitely want the multiprocessing.Process module for this problem, and yes you can use this library (via the Process class) to leverage it. An example may be:

``` Python
from Asynchronous import Process
from multiprocessing import cpu_count()
import socket

n = 1000

@Process
def generate_events(n):
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    sock.connect('/var/run/my_little_socket')
    for _ in range(n):
        sock.send('')
        sock.recv(1024)

event_generators = [generate_events(n) for _ in range(cpu_count())]
for generator in event_generators:
    generator.join()
```

How you give the "go-code" is entirely up to you. These threads will spin up, one after another, rather quickly so I don't think it's worthwhile to attempting scheduling or to share a flag (unless you are intent on making this a pool of workers to periodically fire out tests.).

As a heads up, data safety is still entirely up to you and sys.stdout and and socket.socket are _NOT_ thread safe. So do not attempt to share one instance of these objects without the use of a locking mechanism (check out [multiprocess.Lock](https://docs.python.org/2/library/multiprocessing.html#synchronization-between-processes)).

UPDATED:
Use cpu_count() to only spin up a number of threads equal to the number of CPUs you have.

**Comment by hhcalder92** [comment]
I will try it out! thanks Chris

**Comment by hhcalder92** [comment]
I tested your code and was only able to get the events to be produced once for each process. Any thoughts?

**Comment by christopher-henderson** [comment]
Right, exactly. The body of the target function is turned into its own process. Once its body falls through the process is terminated and the status code is returned. In my example, I do one loop and drop out. It's done. No Frills. If you want these functions to run again, you have to call them again. For this small application that may not be so bad, and would definitely be the easy way out.

``` Python
from Asynchronous import Process
from multiprocessing import cpu_count
from time import sleep
import socket

EVENTS_TO_GENERATE = 1000  # Number of events to generate per process.
REFRACTORY_PERIOD = 5  # In seconds

@Process
def generate_events(n):
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    sock.connect('/var/run/my_little_socket')
    for _ in range(n):
        sock.send('')
        sock.recv(1024)

def go_go_go(n):
    event_generators = [generate_events(n) for _ in range(cpu_count())]
    for generator in event_generators:
        generator.join()

def main():
    while True:
        go_go_go(EVENTS_TO_GENERATE)
        sleep(REFRACTORY_PERIOD)

if __name__ == '__main__':
    main()
```

This is easy and will likely work for you, but is a bit of an anti-pattern. multiprocess.Process is not free to spin to up. A MUCH more common solution to this is the process **pool** which is a pool of worker processes that you can give arbitrary work at arbitrary times. I do not provide a wrapper for this, so you'll have to checkout [multiprocessing.Pool](https://docs.python.org/2/library/multiprocessing.html#module-multiprocessing.pool) yourself.

**Comment by hhcalder92** [comment]
i understand, I applied this to the code and the same thing happens.. 

After some further analysis on the issue, it looks like the one event per process gets sent AFTER i hit CTRL+C

**Comment by christopher-henderson** [comment]
I included a

``` Python
sock.recv(1024)
```

...because it is common for the server to send an ACK response. But if your server sends no such ACK then the client will send exactly one event and then sit on _sock.recv_ indefinitely.

**Comment by hhcalder92** [comment]
i just saw that, now out of 1000 (per example), i only get ~80 per second

Seems as if only one process is doing work? 

UPDATED: 
I have 16 cores

**Comment by christopher-henderson** [comment]
Well, probably not. Multiprocessing has overhead. Quite a lot of it. os.fork has to copy memory and spin up a whole new interpreter. Doing all of that work just to send a thousand empty messages over the wire is likely back firing in terms of performance.

Try multiprocessing.Pool and giving each function more work to do so that you don't spend such a large percentage of your time doing bureaucratic work

**Comment by hhcalder92** [comment]
I was just having some indenting issues.. haha thanks alot Chris! 

Great tool!

**Comment by christopher-henderson** [comment]
hahahah yeah, getting tracebacks from crashing subprocess can be tricky to diagnose.

I hope you see the performance gains you're looking for!
